version: '3'


# NGINX 
# FLASK
# MONGODB
# REDIS
# REDIS WORKER
# TOR + HA PROXY
# [-] MONGOCLIENT 


networks:
  app-tier:
    driver: bridge


services:
  #data bus
  redis:
    image: 'bitnami/redis:latest'
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier

  mongodb:
    image: 'bitnami/mongodb:latest'
    hostname: mongodb
    volumes:
      - .:/bitnami
    ports:
      - "27017:27017"
    environment:
        - MONGODB_ROOT_PASSWORD=123qwe
        - MONGODB_USERNAME=admin
        - MONGODB_PASSWORD=123qwe
        - MONGODB_DATABASE=crawler
    networks:
      - app-tier

  # proxy load balancer
  torpool:
    image: 'zeta0/alpine-tor'
    hostname: torpool
    ports:
      - "5566:5566"
      - "2090:2090"
    environment:
      - tors=5
#      - privoxy=1
    networks:
#      - default
      - app-tier


  server:
    restart: always
    image: nginx
    volumes:
      - ./web-server/conf.d:/etc/nginx/conf.d
      - ./application/web/static:/app/static
    links:
      - web-app:web-app
    ports:
      - "80:80"
    networks:
      - app-tier

  splash:
    image: scrapinghub/splash
    networks:
      - app-tier
    ports:
      - 5023:8050
#    volumes:
#      - ./splash/proxy-profiles:/etc/splash/proxy-profiles:ro

  # application
  web-app:
    restart: always
    build: ./application
    image: web-app
    container_name: web-app
#    command: python app.py
    command: bash -c "/wait && gunicorn app:app -b :8000 --name app --log-level=debug --log-file=-"
    volumes:
       - ./application:/app
#    ports:
#      - "5050:5050"
    expose:
       - "8000"
    depends_on:
       - mongodb
    links:
       - mongodb
       - torpool
       - redis
       - rq-worker
    networks:
       - app-tier
    environment:
      WAIT_HOSTS: mongodb:27017
      WAIT_BEFORE_HOSTS: 25

  rq-worker:
     restart: always
     build: ./application
     container_name: rq-worker
     command: bash -c "/wait && python worker.py"
     networks:
      - app-tier
     volumes:
      - ./application:/app
     depends_on:
      - redis
     links:
      - torpool
      - redis
      - mongodb
     environment:
      WAIT_HOSTS: redis:6379
      WAIT_BEFORE_HOSTS: 5



  mongoclient:
    image: mongoclient/mongoclient
    ports:
      - 3000:3000
    links:
      - mongodb:mongo
    networks:
      - app-tier
